### Employee Login
POST http://localhost:5067/api/auth/login
Content-Type: application/json

{
    "email": "afzal@example.com",
    "password": "Employee@12345"
}
### HR Login
POST http://localhost:5067/api/auth/login
Content-Type: application/json

{
    "email": "hr@hrms.com",
    "password": "HR@12345a"
}
### Employee Check-In
POST http://localhost:5067/api/attendance/check-in
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzI1NDksImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.ml55U_aG5ttDua2hJSk3uxSQf3jleby5OjgiXWIaD4M

### Employee Check-Out
POST http://localhost:5067/api/attendance/check-out
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzI1NDksImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.ml55U_aG5ttDua2hJSk3uxSQf3jleby5OjgiXWIaD4M

### Employee Attendance History
GET http://localhost:5067/api/attendance/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzI1NDksImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.ml55U_aG5ttDua2hJSk3uxSQf3jleby5OjgiXWIaD4M

### HR - View All Attendance
GET http://localhost:5067/api/attendance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ

### HR - View Employee Attendance
GET http://localhost:5067/api/attendance/employee/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ

### Employee - Apply for Leave
POST http://localhost:5067/api/LeaveRequests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzI1NDksImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.ml55U_aG5ttDua2hJSk3uxSQf3jleby5OjgiXWIaD4M
Content-Type: application/json

{
    "startDate": "2026-10-05",
    "endDate": "2026-10-07",
    "leaveType": "Casual",
    "reason": "Personal work"
}

### Employee - My Leave Requests
GET http://localhost:5067/api/LeaveRequests/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzI1NDksImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.ml55U_aG5ttDua2hJSk3uxSQf3jleby5OjgiXWIaD4M

### HR - View All Leave Requests
GET http://localhost:5067/api/LeaveRequests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ

### HR - Approve Leave
PUT http://localhost:5067/api/LeaveRequests/1/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ

### Employee - Apply Another Leave
POST http://localhost:5067/api/LeaveRequests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzI1NDksImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.ml55U_aG5ttDua2hJSk3uxSQf3jleby5OjgiXWIaD4M
Content-Type: application/json

{
    "startDate": "2026-10-10",
    "endDate": "2026-10-11",
    "leaveType": "Sick",
    "reason": "Not feeling well"
}
### HR - Reject Leave
PUT http://localhost:5067/api/LeaveRequests/2/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ

### HR - Create Payroll
POST http://localhost:5067/api/Payroll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ



Content-Type: application/json

{
    "employeeId": 1,
    "basicSalary": 50000,
    "allowances": 10000,
    "deductions": 5000,
    "payDate": "2026-10-01"
}

### TEST PAYROLL
POST http://localhost:5067/api/Payroll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ
Content-Type: application/json

{
    "employeeId": 1,
    "basicSalary": 50000,
    "allowances": 10000,
    "deductions": 5000,
    "payDate": "2026-10-01T00:00:00"
}

### HR - View All Payroll
GET http://localhost:5067/api/Payroll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTA4ODE4NTQsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.HZdBLRiwhY6vlkrc5xeUDfuHvL1cU3bClI51R_1sFTQ

### Employee - View My Payroll
GET http://localhost:5067/api/Payroll/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTA4NzQ2NTEsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.z1o7HuiXGr_0M3hfD4TiU2Ysdac-3yW6Hc47izQKcYw

### TEST 1 - Employee tries to view all payroll
GET http://localhost:5067/api/Payroll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTEwNzY2MDEsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.QZDWIGflaTBVJl4_09tOL8N0aFNVeYVRyLfHXRbldOA

### TEST 2 - HR views all payroll
GET http://localhost:5067/api/Payroll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQ4MGRjNGY2LWUzNjItNGFjZi1iOGM3LTE1Nzg4NjQ2YmFiZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImhyQGhybXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSFIiLCJleHAiOjE3OTEwNzY2NTIsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.T3X-CCBZ6vbmmb0YVmw3Iv5uZyJl9NgagO-_0fWT0tQ   

### TEST 3 - Employee views own payroll
GET http://localhost:5067/api/Payroll/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijg5MmFmZjNlLWQ1MjAtNDkzOS05ZjNjLTBiZTdjNjdlMzFmOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFmemFsQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZWUiLCJleHAiOjE3OTEwNzY2MDEsImlzcyI6IkhSTVMuQVBJIiwiYXVkIjoiSFJNUy5SZWFjdCJ9.QZDWIGflaTBVJl4_09tOL8N0aFNVeYVRyLfHXRbldOA
